# Workflow: branch-test
name: branch-test
on:
  pull_request:
  merge_group:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        run: sleep 30
  build:
      runs-on: ubuntu-latest
      if: github.event_name == 'merge_group'
      steps:
        - name: Sleep for 60 seconds
          run: sleep 60
