# Workflow: main-branch
name: main-branch
on:
  push:
    branches:
      - main
  merge_group:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print event name
        run: |
          THINGIE="${{ github.event_name }}"
          echo "Expand the thingie above."
      - name: Print github context
        run: echo "${{ toJSON(github) }}"
      - name: Print github.event as JSON
        run: echo "${{ toJSON(github.event) }}"
        
